set-up
setUp 

user1:=User username: 'emma.pusso' password: '1qaz2wsx'.
user2:=User username: 'agus.diaz' password: '2wsx3edc'.
topic1:= Topic name: 'topicUno' description: 'topicUno'.
topic2:=Topic name: 'topicDos' description: 'topicDos'.
question2:= Question title: 'question dos' creator: user2 text: 'question 2' topic: topic1.
question1:= Question title: 'question uno' creator: user1 text: 'question 1' topic: topic1.
